name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t NTU-cloud-native-hw4/hello-world-python:latest .

      - name: Push Docker Image (only on push)
        if: github.event_name == 'push'
        run: docker push NTU-cloud-native-hw4/hello-world-python:latest
